<?php
echo"<h1>Operadores Aritmeticos</h1>";
echo'<br>';
echo'<br>';
echo'<br>';
echo"<h2>Suma</h2>";
$numero1= 100;
$numero2= 50;
$resultado= $numero1 + $numero2;
echo'<br>';
echo'<br>';
echo "El resultado de la suma de los numero $numero1 y $numero2 es: " .$resultado;
echo'<br>';
echo'<br>';
echo"<h2>Resta</h2>";
$numer1= 100;
$numer2= 50;
$resultado1= $numer1 - $numer2;
echo'<br>';
echo'<br>';
echo "El resultado de la resta de los numero $numer1 y $numer2 es: " .$resultado1;
echo'<br>';
echo'<br>';
echo"<h2>Multiplicación</h2>";
$nume1= 100;
$nume2= 50;
$resultado2= $nume1 * $nume2;
echo'<br>';
echo'<br>';
echo "El resultado de la multiplicacion de los numero $nume1 y $nume2 es: " .$resultado2;
echo'<br>';
echo'<br>';
echo"<h2>División</h2>";
$num1= 100;
$num2= 50;
$resultado3= $num1 / $num2;
echo'<br>';
echo'<br>';
echo "El resultado de la multiplicacion de los numero $num1 y $num2 es: " .$resultado3;
echo'<br>';
echo'<br>';
echo"<h2>Modulo</h2>";
$n1= 100;
$n2= 50;
$resultado4= $n1 % $n2;
echo'<br>';
echo'<br>';
echo "El resultado de la multiplicacion de los numero $n1 y $n2 es: " .$resultado4;
?>